### ISSUE TITLE
file downloader with Python

### ISSUE THREAD

**Issue by BDadmehr0** [BDadmehr0/OpenGameZone#1]
Create a file downloader with Python in the directory **/home/ < username > /OpenGameZone/ < GameName >**
Download games from our host

**Comment by bhargavnova** [comment]
can assign this to me?

**Comment by BDadmehr0** [comment]
> can assign this to me?

Yes, I will be happy to help

**Comment by BDadmehr0** [comment]
I suggest that you write the code in a folder called lib
Write the code in a functional way so that it can be used in other codes.

```python
def download_file(link):
    print(f'File downloaded from the link: {link}')

# Example usage of the function:
file_link = "https://example.com/file.txt"
download_file(file_link)
```

**Comment by bhargavnova** [comment]
Sure!!

**Comment by BDadmehr0** [comment]
Thanks for the contribution
